name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint and run test
        run: |
          yarn run lint
          yarn run test
      - name: Build
        run: yarn run build
        env:
          CI: true
